### PR TITLE
SVGView: make subclassable

### PR DESCRIPTION
**Pull request by Lupurus**
Make SVGView subclassable by making svgNode, rootNode and render() public.

### CODE REVIEW

**Comment by ystrot** [comment]
I've already mentioned this in one of the comments. The thing is `SVGView` is not intended to be subclassed or reused. All these properties and methods are internal implementation and can be changed in future, so we can't make it part of the public API. The right solution would be to move all useful code from `SVGView` to `MacawView` and use `MacawView` directly.

**Comment by Lupurus** [comment]
Ok, than sorry for this pull request. So would you mind about if I add the contentMode-property to MacawView?

**Comment by ystrot** [comment]
I think we can do something even better then content mode property in MacawView. Please give me some time to make a draft API changes necessary to implement this feature and then we'll be happy if you can work on the implementation 😊

**Comment by Lupurus** [comment]
Can I add some additional ideas to it? I just run into the problem, that I want to draw something to a button. This is actually not "possible" directly, because you need a `MacawView` or a `SVGView`. I managed it by parsing my SVG to a `Node`. Then I transformed the size using your code from `.scaleAspectFit`. Then I created a new `RenderContext` (view can be `nil`), set the `cgContext` to `MGraphicsGetCurrentContext()` and then I finally created a `NodeRenderer` with `RenderUtils.createNodeRenderer(...)`. All this one I put into the `draw`-function of my sucblassed view.

So what do you think about any way to support directly drawing a node? Maybe you can implement the resizing code in the renderer? So maybe you could do something like this:

```
override func draw(_ dirtyRect: NSRect) {
    super.draw(dirtyRect)
    let svgNode = SVGParser.parse(path: "mySVG")
    svgNode.drawHere(bounds: self.frame)
```

The work of the `drawHere(bounds: )` function would be to create a NodeRenderer, using the currentContext and resize it to the given bounds. The view of the `RenderContext` can be `nil`.

By the way... Merry Christmas :)

**Comment by ystrot** [comment]
I think the easiest way would be to draw SVG to an image and then draw to your button or any other place. Here is the code sample https://github.com/exyte/Macaw/issues/65#issuecomment-257495827

P.S. Please feel free to open a new issue for your questions, because it's sometimes hard to find your question in a closed ticket 😉 Happy New Year!

**Pull request closed without merging**
