### PR TITLE
Added node search by predicate

### PR DESCRIPTION
**Pull request by AntonPoltoratskyi**
### Intention
- Sometimes we want to search by some custom predicate. We may want to search by some id's prefix, regex, etc.

### Updates
- `func nodeBy(tag:)` is left, but added `func nodeBy(predicate:)` which is more customisable (see 'Intention' paragraph).

### CODE REVIEW

**Comment by ystrot** [comment]
Hi @AntonPoltoratskyi!

I think it's a good idea, however it would be better to have even more generic approach:
```Swift
func nodeBy(predicate: (Node) -> Bool) -> Node?

func nodesBy(predicate: (Node) -> Bool) -> [Node]
```

Could you please update your PR so I can merge your work?

**Comment by AntonPoltoratskyi** [comment]
Sure, I will push updates today or tomorrow

**Comment by AntonPoltoratskyi** [comment]
Hi @ystrot ! I pushed updates

**Comment by ystrot** [comment]
Awesome, thank you! Merged it.

**Pull request merged**
