### PR TITLE
Added support of kerning to Text

### PR DESCRIPTION
**Pull request by K-Be**
Added support of kerning to Text. 
Faced with a [strange problem](https://stackoverflow.com/questions/54948326/inconsistent-behavior-of-kerning-in-nsattributedstring) with kerning and phrase "Hello, world", but in other cases kerning has correct behaviour. I think, it is a bug of NSAttributedString.

### CODE REVIEW

**Comment by ystrot** [comment]
Hi Andrew,

Thank you for your work! I'll review it and merge in the beginning of the next week.

**Comment by K-Be** [comment]
What do think about make kerning property an optional property?

**Comment by ystrot** [comment]
I was thinking about this, however logically no kerning equals to kerning = 0, so I think zero value is fine.

**Comment by K-Be** [comment]
With and without 0 the kerning has different behaviour (look at link that I've added to my PR).    
I do not add Kern attribute to NSAttributedString if kerning is equal 0.

**Comment by ystrot** [comment]
Hi Andrew,

I agree, no matter how it works, logically zero kerning means no kerning and we don't need to fix API to match current implementation. So your workaround is fine. I'm going to merge your patch now. Thank you for your work!

**Pull request merged**
