### PR TITLE
Support convert to native image from Operation queue background thread

### PR DESCRIPTION
**Pull request by pnghitink33b**

### CODE REVIEW

**Comment by amarunko** [comment]
Hi, @pnghitink33b , what's wrong with the current realization? As I know it is work from any thread too. Please, correct me if I wrong.

**Comment by pnghitink33b** [comment]
Hello @amarunko, 
I use concurrent NSOperation to convert multiple svg UIImage At same time and MGraphicsGetCurrentContext()! return nil.
Screen Shot 2020-02-27 at 3 17 02 PM

**Comment by amarunko** [comment]
Size != .zero?

**Comment by pnghitink33b** [comment]
Ah, reason it crash is size equal to zero. I wrong. Thanks you. 
And I think call render.dispose method after draw will reduce memory usage, right?

**Comment by amarunko** [comment]
According to previous logic - all will be destroyed on deinit method. I think it is not needed, did you check on memory leaks?

**Pull request closed without merging**
