### PR TITLE
Text fixes

### PR DESCRIPTION
**Pull request by rFlex**
- Using bottom as default baseline. I also think the current calculation for the baseline might be a little off, will look a little more in detail when I have the time.
- font-size attributes can end with "px", this change allows that.

### CODE REVIEW

**Comment by kayuri** [comment]
- Changing baseline default value looks too risky at this point. 
- Allowing px looks good though. If you don't mind I will extract this into a separate PR and merge it?

**Comment by rFlex** [comment]
Please do not close and do the changes yourself. In open source you should allow external contributors to get proper attribution on their work.

Do you have an SVG example where baseline top should be the default? In my test SVGs Macaw doesn't render the text at the right location at all compared to Chrome or even SVGKit. Changing the baseline fixes it.

**Comment by kayuri** [comment]
@rFlex my apologies, sure

**Comment by rFlex** [comment]
@kayuri I agree that it might break existing code, not sure how to work around that because the problem is that the current behavior seems incorrect.

Example SVG:
```
<svg
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:jfreesvg="http://www.jfree.org/jfreesvg/svg" viewBox="0 0 500 500" shape-rendering="auto">
    <rect x="0" y="0" width="500" height="500" style="fill: rgb(147,220,254); fill-opacity: 1.0" transform="matrix(1,0,0,1,0,0)"/>
    <text x="120" y="250" style="fill: rgb(255,255,255); fill-opacity: 1.0; font-family: Comic Sans MS; font-size: 40px;">This is a test</text>
    <rect x="120" y="253" width="250" height="2" style="fill: yellow; fill-opacity: 1.0" transform="matrix(1,0,0,1,0,0)"/>    
</svg>
``` 

How Chrome renders it:
screen shot 2017-09-20 at 10 12 05 am

How Macaw renders it:
screen shot 2017-09-20 at 10 11 51 am

**Comment by kayuri** [comment]
I think we can probably just change the way our parser works, e.g.  in SVGParser change parseSimpleText method and create object with `baseline:.bottom` by default. This will work for your case. Would be better of course to properly parse baseline and make it work for all cases, but at least this would fix the default case. I can prepare this quick fix if you want.

**Comment by kayuri** [comment]
@rFlex I took a liberty of making a quick fix for text baseline. Works fine for SVG from your comment.

**Comment by rFlex** [comment]
got it @kayuri , updated!

**Comment by ystrot** [comment]
Hi Simon,

Sorry for delay from Macaw Team. I'm going to apply all your patches in the nearest time. Hope you'll be available for little fixes if necessary. Regarding this issue, could you please create pull request with only [this commit](https://github.com/exyte/Macaw/pull/156/commits/3b7d24e0448cf092f1b0c5551da8c17de35d381e) which related to this issue?

Other changes related to implementing `CustomStringConvertible` and `Equatable` protocols also seems useful, but they need to be consistent (not only `Rect` and `Point`, but other classes should be affected) and independent (there should be another pull request with only these changes).

**Comment by ystrot** [comment]
These issues were fixed as part of the SVG parser improvements (see https://github.com/f3dm76/Macaw/commit/843cac6b6d3cec585e17c4ee99dd38a898cb8bf7)

**Pull request closed without merging**
