### PR TITLE
Feature/uiimage support

### PR DESCRIPTION
**Pull request by evnaz**
Hi,

I'm trying to implement an extension to create `UIImage` from SVG file.
I used `NodeRenderer.renderToImage()` for that. For some reason the image is always empty.
Can anybody advise me what is wrong here? Are there any plans to have such functionality?

Thanks

### CODE REVIEW

**Comment by ystrot** [comment]
Hi Eugene,

You don't need to write your extension, you can use something like this:
```
func svgToImge(resourceName: String, size: CGSize) -> UIImage {
    let rootNode = SVGParser.parse(path: resourceName)
    let macawView = MacawView(node: rootNode, frame:CGRect(origin: CGPoint.zero, size: size))
    UIGraphicsBeginImageContext(size)
    macawView.layer.render(in: UIGraphicsGetCurrentContext()!)
    let img =  UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return img!
}
```

**Comment by evnaz** [comment]
Hi @ystrot,

The benefits of an `UIImage` extension are
- avoiding redundant image drawing (since the SVG's already drawn inside the `MacawView`)
- having easy to use interface for image creating

Wouldn't it be great to have such feature as a part of the lib and not a workaround?

**Comment by Quanhua-Guan** [comment]
when use MacawView, it has to be in main thread. however, we need to get the image in background thread. @ystrot

**Comment by BrettAtMangoHealth** [comment]
Hi @ystrot,
Similarly to @Quanhua-Guan, our team is trying to retrieve the image in a background thread and cannot use a MacawView + the code snippet you provided to get the job done as it results in a blank (and black) image.

**Comment by amarunko** [comment]
Hello, @lubiluk, why do you think so? For me this extension working for a case, when MacawView not in view hierarchy right now. Can you explain your problem if it exists in little details?

**Comment by lubiluk** [comment]
Now when I tested it again it renders an image just fine. Sorry!

**Comment by ystrot** [comment]
Hi Eugene,

Thanks you for your proposal. Now this feature available through `Node.toNativeImage(size:layout:)` method.

Sorry we didn't take your original PR. Final implementation was quite different from the solution you provided, in particular:
* `Node` extension is more natural for Macaw API than `UIImage` extension.
* It's better to convert node rather than SVG file to an image, because you can create a scene without using SVG.
* Such a method should also handle content layout properly, etc.

Anyway, let us know if you'll find something else to improve in Macaw and we'll be happy to approve your work next time.

**Pull request closed without merging**
