### PR TITLE
Quadratic path support

### PR DESCRIPTION
**Pull request by rFlex**
Support for Q path. Unclear whether q will properly work with this change, I don't have an example that uses it unfortunately :(.

### CODE REVIEW

**Comment by kayuri** [comment]
Nope, doesn't work even on simple examples:
```
<?xml version="1.0"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
         "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     height="800">
 <g>
<path d="M 10 35 q 15 -30 30 0" stroke="blue"
  stroke-width="5" fill="none" />
</g>
</svg>
```
I will try to have a closer look but seems like the TODO in code needs to be addressed :)

**Comment by rFlex** [comment]
@kayuri I just updated the example and SVGView to allow setting an external url (easier to test local files from the example and it's a useful feature anyway). Beside the incorrect inferred bounds, it seems to work properly on your example. I can look at why the bounds are incorrect in the first place, unclear whether this is related to my change though.

screen shot 2017-09-08 at 11 56 31 am

**Comment by rFlex** [comment]
@kayuri Example with bounding box working. In the latest commit I'm using CGPath boundingBox instead of the custom calculation code. You may have good reasons why you made that code in the first place, let me know if you want me to revert that change.

screen shot 2017-09-08 at 12 04 47 pm

**Comment by kayuri** [comment]
@rFlex yep, I got similar views, though that bounds issue was caused by the the change though. Will give it some more thought. Thanks!

**Comment by rFlex** [comment]
@kayuri yes it's because it was missing the implementation to return the bounds from a Q/q Path, which causes problems when trying to scale the view.

**Comment by ystrot** [comment]
Hi Simon,

Generally your patch looks good. Could you please update it to the latest version and avoid merge conflicts?

**Comment by ystrot** [comment]
Hi Simon,

Unfortunately we were unable to apply your patch, because it was outdated. However we implemented quadratic segments (including q/Q/t/T types) and it's already in the master and will be part of 0.9.2 release.

**Pull request closed without merging**
