### PR TITLE
Linear gradient: improvements

### PR DESCRIPTION
**Pull request by Lupurus**
I added some Docstrings to the LinearGradient and as well I added an additional init, so that you can init the LinearGradient with a degree and multiple Stop.

### CODE REVIEW

**Comment by ystrot** [comment]
Looks like you mixed your LinearGradient changes with Text changes. I'm actually started to work on #238 and there are some more issues need to be addressed, so if you don't mind I'd like to finish this work myself. But if you would be able to work on documentation as I suggested in #245 - it would be great.

**Comment by Lupurus** [comment]
Sure, thank you and sorry! These are my first steps with GitHub!

**Comment by Lupurus** [comment]
Sorry for that question (here), I just saw this: If I create a new branch, it will also have the changes of the other branches. For different tasks, do I have to make different forks? I don't see an option for creating a branch from the master branch without having the other changes ...

**Comment by zapletnev** [comment]
Hi @Lupurus,

I would like to suggest next workflow:
1. Make fork. You already have it: https://github.com/Lupurus/Macaw
2. Make a feature branch from master
3. Make all required changes to one specific task
4. Commit and push this new branch
5. Make PR in the original repository exyte/Macaw
6. Make a new branch from master (it doesn't have any changes!) for different task
7. Repeat 3 4 5.

After merging your PR or any other changes in the original Macaw you have to update your fork. At first, you need to add origin remote (you need to do it once):
git remote add upstream https://github.com/exyte/Macaw.git

After to update the fork:
1. git fetch upstream  
2. git checkout master
3. git merge upstream/master

**Comment by zapletnev** [comment]
@Lupurus thanks for your contribution!

**Pull request closed without merging**
